wandb_version: 1

model_name:
  desc: null
  value: bert-base-uncased
seed:
  desc: null
  value: 42
dataset_name:
  desc: null
  value: glue
subset_name:
  desc: null
  value: mrpc
task_type:
  desc: null
  value: sequence
_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1700665725.531945
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.10.10
      5: 0.16.0
      6: 4.35.0
      8:
      - 3
      - 5
      13: windows-amd64
